# Generated by Django 4.1.7 on 2023-03-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('notes', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='user_propery_images')),
                ('price', models.IntegerField(default=0)),
                ('safety', models.IntegerField(default=0)),
                ('convenience', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
            ],
        ),
    ]
