# Generated by Django 4.1.7 on 2023-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_property_building_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_age',
            field=models.CharField(choices=[('1', 'Less than 5 years'), ('0.5', 'Less than 10 years'), ('0', 'More than 10 years')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_codes',
            field=models.CharField(choices=[('1', 'Yes'), ('0.5', 'Unsure'), ('0', 'No')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='fault_line',
            field=models.CharField(choices=[('1', 'No'), ('0.5', 'Less than 1 kilometer away from a fault line'), ('0', 'Less than 5 meters away from or directly on top of a fault line')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='foundation_issues',
            field=models.CharField(choices=[('1', 'No issues/Resolved issues'), ('0.5', 'Issues present, unsure if resolve'), ('0', 'Issues present and unresolve')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(choices=[('1', 'Within budget'), ('0', 'Overbudget')], max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='retrofitted',
            field=models.CharField(choices=[('1', "Yes/Doesn't need retrofitting at present"), ('0.5', 'Unsure'), ('0', 'Needs to undergo retrofitting')], max_length=255),
        ),
    ]
