# Generated by Django 4.1.7 on 2023-04-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_property_building_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='convenience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='safety',
            field=models.IntegerField(default=0),
        ),
    ]
