# Generated by Django 4.1.7 on 2023-04-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_property_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bills_payment_center',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='fire_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='gas_station_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='grocery_or_market',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='hospital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='laundromat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='mall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='police_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='transport_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='water_filling_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='workplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='safety',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
