# Generated by Django 4.1.7 on 2023-04-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_property_bills_payment_center_property_fire_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='other_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
